"""Nearest responders and per-recipient response packets.

The requirement that matters here is that each recipient class gets a *different*
draft. An MRCC needs position, POB and SAR region. A nearby merchant needs the SOLAS
duty-to-assist ask and the hazards it is steaming into. Next of kin needs neither.
Sending one broadcast to all five would be worse than sending nothing.

Every packet is created unapproved. Nothing in this module sends anything.
"""

from __future__ import annotations

import math

from .models import Incident, Packet
from .sim import Ship, haversine_nm

GMDSS_FOOTER = (
    "--\nGenerated by the Seafarers Emergency Support Network (SIMULATION). "
    "Decision support only. This system is supplementary to GMDSS and is not a "
    "replacement for it. Distress alerting must be made via GMDSS."
)

# Simulated search-and-rescue regions, matched most-specific first.
#
# Real IMO SAR regions are declared by coastal states and are not public rectangles,
# so these are an approximation good enough to name a responsible authority rather
# than a coordinate. The MRCC designators are deliberately fictional: this system
# must never put a real rescue coordination centre's details in front of an operator
# running a simulation.
#
# Coverage is exhaustive by construction: the chokepoint boxes below handle the
# cases worth naming precisely, and `_basin` catches everything else. An incident
# that cannot be attributed to an authority is a bug, and `test_sar_coverage` fails
# if one ever appears.
SAR_REGIONS: list[tuple[str, str, tuple[float, float, float, float]]] = [
    ("Gulf of Aden / Bab el-Mandeb", "MRCC SIM-ADEN", (10.0, 41.0, 16.0, 52.0)),
    ("Red Sea / Suez Approaches", "MRCC SIM-SUEZ", (16.0, 32.0, 31.5, 44.0)),
    ("Arabian Gulf / Hormuz", "MRCC SIM-HORMUZ", (23.0, 47.0, 31.0, 58.0)),
    ("Singapore Strait / Malacca", "MRCC SIM-MALACCA", (-2.0, 95.0, 8.0, 106.0)),
    ("Dover Strait / Southern North Sea", "MRCC SIM-CHANNEL", (48.5, -4.0, 54.0, 9.0)),
    ("Baltic Approaches", "MRCC SIM-BALTIC", (53.0, 9.0, 66.0, 30.0)),
    ("Mediterranean", "MRCC SIM-MEDITERRANEAN", (30.0, -6.0, 46.0, 36.5)),
    ("Black Sea", "MRCC SIM-EUXINE", (40.0, 27.0, 47.5, 42.0)),
    ("Panama / Caribbean Approaches", "MRCC SIM-CARIBE", (5.0, -90.0, 25.0, -58.0)),
    ("Bay of Bengal", "MRCC SIM-BENGAL", (5.0, 78.0, 23.0, 95.0)),
    ("South China Sea", "MRCC SIM-NANHAI", (2.0, 105.0, 24.0, 122.0)),
    ("East China Sea / Korea Strait", "MRCC SIM-DONGHAI", (24.0, 118.0, 39.0, 131.0)),
    ("Japan / Kuroshio", "MRCC SIM-KUROSHIO", (28.0, 129.0, 46.0, 150.0)),
    ("Southern Africa / Cape", "MRCC SIM-CAPE", (-40.0, 14.0, -24.0, 36.0)),
    ("Gulf of Guinea", "MRCC SIM-GUINEA", (-10.0, -6.0, 8.0, 14.0)),
    ("Australia / Tasman", "MRCC SIM-TASMAN", (-48.0, 110.0, -9.0, 180.0)),
]


def _basin(lat: float, lon: float) -> tuple[str, str]:
    """Ocean-basin fallback. Every position on earth resolves to an authority here,
    because "we could not work out whose water this is" is not an answer a rescue
    coordination system is allowed to give."""
    if lat >= 66.0:
        return "Arctic Ocean", "MRCC SIM-ARCTIC"
    if lat <= -60.0:
        return "Southern Ocean", "MRCC SIM-AUSTRAL"
    if -100.0 <= lon <= 25.0:
        return ("North Atlantic", "MRCC SIM-ATLANTIC-N") if lat >= 0 else \
               ("South Atlantic", "MRCC SIM-ATLANTIC-S")
    if 25.0 < lon <= 120.0:
        return ("Arabian Sea / North Indian Ocean", "MRCC SIM-INDIAN-N") if lat >= 0 else \
               ("South Indian Ocean", "MRCC SIM-INDIAN-S")
    return ("North Pacific", "MRCC SIM-PACIFIC-N") if lat >= 0 else \
           ("South Pacific", "MRCC SIM-PACIFIC-S")



def sar_region(lat: float, lon: float) -> tuple[str, str]:
    for name, mrcc, (s, w, n, e) in SAR_REGIONS:
        if s <= lat <= n and w <= lon <= e:
            return name, mrcc
    return _basin(lat, lon)


def nearest(vessels: list[Ship], to: Ship, limit: int = 5) -> list[dict]:
    """Haversine sort. With a few hundred vessels in memory this is a scan, and a
    scan is correct. PostGIS KNN earns its place when that stops being true."""
    # Bounding-box prefilter before any trigonometry. A responder 400 nm away is not
    # a responder, and haversine over the whole 60k fleet to establish that is waste.
    window = 8.0  # degrees, generously more than the ~400 nm we care about
    lon_window = window / max(0.2, math.cos(math.radians(to.lat)))

    out = []
    for v in vessels:
        if v.mmsi == to.mmsi or v.distressed or v.pob == 0:
            continue
        if abs(v.lat - to.lat) > window or abs(v.lon - to.lon) > lon_window:
            continue
        nm = haversine_nm(to.lat, to.lon, v.lat, v.lon)
        eta = nm / v.speed_kn if v.speed_kn > 0.5 else None
        out.append({
            "mmsi": v.mmsi, "name": v.name, "kind": v.kind,
            "distance_nm": round(nm, 1),
            "eta_hours": round(eta, 1) if eta else None,
            "sar_capable": v.can_assist,
        })
    # Dedicated SAR assets first at comparable range, then pure proximity.
    out.sort(key=lambda r: (r["distance_nm"] - (60.0 if r["sar_capable"] else 0.0)))
    return out[:limit]


def _position(lat: float, lon: float) -> str:
    ns, ew = ("N" if lat >= 0 else "S"), ("E" if lon >= 0 else "W")
    return f"{abs(lat):.3f}{ns} {abs(lon):.3f}{ew}"


def build_packets(incident: Incident, vessel: Ship, responders: list[dict]) -> list[Packet]:
    t = incident.triage
    assert t is not None, "packets requested before triage"

    region, mrcc = sar_region(vessel.lat, vessel.lon)
    pos = _position(vessel.lat, vessel.lon)
    unknowns = "\n".join(f"  - {u}" for u in t.unknowns) or "  - none declared"
    closest = responders[0] if responders else None
    sar_assets = [r for r in responders if r["sar_capable"]]

    packets = [
        Packet(
            recipient_class="mrcc",
            recipient_name=f"{mrcc} ({region})",
            subject=f"[{t.severity.name}] {t.type.value}: {vessel.name} ({vessel.mmsi})",
            body=(
                f"INCIDENT CLASSIFICATION: {t.type.value}\n"
                f"SEVERITY: {t.severity.name}\n"
                f"CONFIDENCE: {t.confidence:.2f} (classifier: {t.provider})\n\n"
                f"VESSEL: {vessel.name}\nMMSI: {vessel.mmsi}\n"
                f"FLAG: {vessel.flag}\nTYPE: {vessel.kind}\n"
                f"PERSONS ON BOARD: {vessel.pob}\n\n"
                f"POSITION: {pos}\n"
                f"COURSE/SPEED: {vessel.course:.0f}T / {vessel.speed_kn:.1f} kn\n"
                f"NAV STATUS: {vessel.nav_status}\n"
                f"SAR REGION: {region}\n\n"
                f"UNCONFIRMED AT TIME OF SENDING:\n{unknowns}\n\n"
                f"BASIS: {t.rationale}\n\n{GMDSS_FOOTER}"
            ),
        ),
    ]

    if closest:
        packets.append(Packet(
            recipient_class="merchant",
            recipient_name=f"{closest['name']} ({closest['mmsi']})",
            subject=f"Request to assist. Vessel in distress {closest['distance_nm']} nm from you",
            body=(
                f"Master, {closest['name']}.\n\n"
                f"A vessel in your vicinity is in distress and you may be the closest "
                f"hull. This is a request under the SOLAS duty to render assistance.\n\n"
                f"CASUALTY: {vessel.name} ({vessel.mmsi}), {vessel.pob} persons on board\n"
                f"POSITION: {pos}\n"
                f"NATURE: {t.type.value} ({t.severity.name} severity)\n"
                f"YOUR RANGE: {closest['distance_nm']} nm"
                + (f", estimated {closest['eta_hours']} h at current speed\n"
                   if closest['eta_hours'] else "\n")
                + f"\nHAZARDS TO YOU ON APPROACH:\n{_hazards(t.type.value)}\n\n"
                f"If you are able to divert, advise the responsible rescue coordination "
                f"centre and this station. If you are not able to divert, say so. A "
                f"declined request is still information we need.\n\n{GMDSS_FOOTER}"
            ),
        ))

    if sar_assets:
        a = sar_assets[0]
        packets.append(Packet(
            recipient_class="naval",
            recipient_name=f"{a['name']} ({a['kind']}, {a['mmsi']})",
            subject=f"SAR tasking request: {t.type.value}, {a['distance_nm']} nm",
            body=(
                f"CASUALTY: {vessel.name} ({vessel.mmsi})\n"
                f"POSITION: {pos}\nPOB: {vessel.pob}\n"
                f"CLASSIFICATION: {t.type.value} / {t.severity.name} "
                f"(confidence {t.confidence:.2f})\n"
                f"RANGE FROM YOU: {a['distance_nm']} nm"
                + (f", ETA {a['eta_hours']} h\n" if a['eta_hours'] else "\n")
                + f"\nTHREAT PICTURE: {_threat(t.type.value)}\n\n"
                f"UNCONFIRMED:\n{unknowns}\n\n"
                f"This is a request for tasking, not a tasking order. Rules of "
                f"engagement remain a matter for your chain of command.\n\n{GMDSS_FOOTER}"
            ),
        ))

    packets.append(Packet(
        recipient_class="manager",
        recipient_name=f"Designated Person Ashore, {vessel.flag} flag",
        subject=f"{vessel.name}: {t.type.value}, {t.severity.name}",
        body=(
            f"Full picture for the DPA.\n\n"
            f"VESSEL: {vessel.name} ({vessel.mmsi}), {vessel.flag} flag, {vessel.kind}\n"
            f"POB: {vessel.pob}\nPOSITION: {pos}\nCORRIDOR: {vessel.corridor}\n\n"
            f"REPORT AS RECEIVED:\n{incident.report_text or '(no voice or written report)'}\n\n"
            f"TRIAGE: {t.type.value} / {t.severity.name}, confidence {t.confidence:.2f}, "
            f"classifier {t.provider} ({t.latency_ms} ms)\n"
            f"BASIS: {t.rationale}\n\n"
            f"UNCONFIRMED:\n{unknowns}\n\n"
            f"RESPONSIBLE AUTHORITY: {mrcc}, {region}\n"
            f"NEAREST ASSETS: " + ", ".join(
                f"{r['name']} ({r['distance_nm']} nm)" for r in responders[:3]) + "\n\n"
            f"Next of kin notification has been drafted and is held pending your "
            f"instruction. It has not been sent.\n\n{GMDSS_FOOTER}"
        ),
    ))

    packets.append(Packet(
        recipient_class="next_of_kin",
        recipient_name="Next of kin: DRAFT, hold for company welfare officer",
        subject=f"Regarding {vessel.name}",
        body=(
            f"DRAFT ONLY. This must be read, edited and sent by a named human being "
            f"in the company's welfare function. It must not be sent as written and "
            f"it must not be sent by this system.\n\n"
            f"---\n\n"
            f"We are contacting you about {vessel.name}, on which your relative is "
            f"serving. Earlier today the vessel reported an incident and shore "
            f"authorities are involved. We do not yet have confirmed information "
            f"about individual crew members.\n\n"
            f"We will call you again as soon as we have something confirmed, whether "
            f"or not there is news. You can reach the company's welfare line at any "
            f"hour.\n\n---\n\n"
            f"Do not release the vessel position, the incident classification, or the "
            f"confidence figure to next of kin. None of it is confirmed and all of it "
            f"will be quoted back.\n\n{GMDSS_FOOTER}"
        ),
    ))

    return packets


def _hazards(incident_type: str) -> str:
    return {
        "Piracy": "  Armed skiffs may still be in the area. Consider approaching only\n"
                  "  with naval escort. Harden the ship before closing.",
        "Attack": "  Area is subject to aerial and surface attack. Assess your own risk\n"
                  "  before diverting. You are not obliged to enter a threat area.",
        "Fire": "  Fire aboard, possible smoke and heat on the leeward side.\n"
                "  Approach from upwind.",
        "Flooding": "  Casualty may be listing and unstable. Do not moor alongside.",
        "Collision": "  Debris and persons possibly in the water. Reduce speed, post\n"
                     "  extra lookouts.",
        "Grounding": "  Casualty is aground. Uncharted or shoaling water in the\n"
                     "  immediate area. Do not close inside your own safe contour.",
        "CrewAbandonment": "  Survival craft and persons in the water. Reduce speed,\n"
                           "  post extra lookouts, rig recovery.",
        "ManOverboard": "  Person in the water. Reduce speed, post extra lookouts.",
    }.get(incident_type, "  Nature of the incident is not confirmed. Approach with caution.")


def _threat(incident_type: str) -> str:
    return {
        "Piracy": "Armed hostile actors, small craft, likely boarding attempt.",
        "Attack": "Aerial or surface weapon employment against merchant shipping.",
    }.get(incident_type, "No hostile actor indicated. Humanitarian SAR tasking.")
