"""Nearest responders and per-recipient response packets.

The requirement that matters here is that each recipient class gets a *different*
draft. An MRCC needs position, POB and SAR region. A nearby merchant needs the SOLAS
duty-to-assist ask and the hazards it is steaming into. Next of kin needs neither.
Sending one broadcast to all five would be worse than sending nothing.

Every packet is created unapproved. Nothing in this module sends anything.
"""

from __future__ import annotations

import math

from .models import Action, Incident, Packet, Responder, TriageResult
from .sim import ARMED, Ship, haversine_nm

GMDSS_FOOTER = (
    "--\nGenerated by the Seafarers Emergency Support Network (SIMULATION). "
    "Decision support only. This system is supplementary to GMDSS and is not a "
    "replacement for it. Distress alerting must be made via GMDSS."
)

# Simulated search-and-rescue regions, matched most-specific first.
#
# Real IMO SAR regions are declared by coastal states and are not public rectangles,
# so these are an approximation good enough to name a responsible authority rather
# than a coordinate. The MRCC designators are deliberately fictional: this system
# must never put a real rescue coordination centre's details in front of an operator
# running a simulation.
#
# Coverage is exhaustive by construction: the chokepoint boxes below handle the
# cases worth naming precisely, and `_basin` catches everything else. An incident
# that cannot be attributed to an authority is a bug, and `test_sar_coverage` fails
# if one ever appears.
SAR_REGIONS: list[tuple[str, str, tuple[float, float, float, float]]] = [
    ("Gulf of Aden / Bab el-Mandeb", "MRCC SIM-ADEN", (10.0, 41.0, 16.0, 52.0)),
    ("Red Sea / Suez Approaches", "MRCC SIM-SUEZ", (16.0, 32.0, 31.5, 44.0)),
    ("Arabian Gulf / Hormuz", "MRCC SIM-HORMUZ", (23.0, 47.0, 31.0, 58.0)),
    ("Singapore Strait / Malacca", "MRCC SIM-MALACCA", (-2.0, 95.0, 8.0, 106.0)),
    ("Dover Strait / Southern North Sea", "MRCC SIM-CHANNEL", (48.5, -4.0, 54.0, 9.0)),
    ("Baltic Approaches", "MRCC SIM-BALTIC", (53.0, 9.0, 66.0, 30.0)),
    ("Mediterranean", "MRCC SIM-MEDITERRANEAN", (30.0, -6.0, 46.0, 36.5)),
    ("Black Sea", "MRCC SIM-EUXINE", (40.0, 27.0, 47.5, 42.0)),
    ("Panama / Caribbean Approaches", "MRCC SIM-CARIBE", (5.0, -90.0, 25.0, -58.0)),
    ("Bay of Bengal", "MRCC SIM-BENGAL", (5.0, 78.0, 23.0, 95.0)),
    ("South China Sea", "MRCC SIM-NANHAI", (2.0, 105.0, 24.0, 122.0)),
    ("East China Sea / Korea Strait", "MRCC SIM-DONGHAI", (24.0, 118.0, 39.0, 131.0)),
    ("Japan / Kuroshio", "MRCC SIM-KUROSHIO", (28.0, 129.0, 46.0, 150.0)),
    ("Southern Africa / Cape", "MRCC SIM-CAPE", (-40.0, 14.0, -24.0, 36.0)),
    ("Gulf of Guinea", "MRCC SIM-GUINEA", (-10.0, -6.0, 8.0, 14.0)),
    ("Australia / Tasman", "MRCC SIM-TASMAN", (-48.0, 110.0, -9.0, 180.0)),
]


def _basin(lat: float, lon: float) -> tuple[str, str]:
    """Ocean-basin fallback. Every position on earth resolves to an authority here,
    because "we could not work out whose water this is" is not an answer a rescue
    coordination system is allowed to give."""
    if lat >= 66.0:
        return "Arctic Ocean", "MRCC SIM-ARCTIC"
    if lat <= -60.0:
        return "Southern Ocean", "MRCC SIM-AUSTRAL"
    if -100.0 <= lon <= 25.0:
        return ("North Atlantic", "MRCC SIM-ATLANTIC-N") if lat >= 0 else \
               ("South Atlantic", "MRCC SIM-ATLANTIC-S")
    if 25.0 < lon <= 120.0:
        return ("Arabian Sea / North Indian Ocean", "MRCC SIM-INDIAN-N") if lat >= 0 else \
               ("South Indian Ocean", "MRCC SIM-INDIAN-S")
    return ("North Pacific", "MRCC SIM-PACIFIC-N") if lat >= 0 else \
           ("South Pacific", "MRCC SIM-PACIFIC-S")



def sar_region(lat: float, lon: float) -> tuple[str, str]:
    for name, mrcc, (s, w, n, e) in SAR_REGIONS:
        if s <= lat <= n and w <= lon <= e:
            return name, mrcc
    return _basin(lat, lon)


def nearest(vessels: list[Ship], to: Ship, limit: int = 5) -> list[Responder]:
    """Haversine sort. With a few hundred vessels in memory this is a scan, and a
    scan is correct. PostGIS KNN earns its place when that stops being true."""
    # Bounding-box prefilter before any trigonometry. A responder 400 nm away is not
    # a responder, and haversine over the whole 60k fleet to establish that is waste.
    window = 8.0  # degrees, generously more than the ~400 nm we care about
    lon_window = window / max(0.2, math.cos(math.radians(to.lat)))

    out = []
    for v in vessels:
        if v.mmsi == to.mmsi or v.distressed or v.pob == 0:
            continue
        if abs(v.lat - to.lat) > window or abs(v.lon - to.lon) > lon_window:
            continue
        nm = haversine_nm(to.lat, to.lon, v.lat, v.lon)
        eta = nm / v.speed_kn if v.speed_kn > 0.5 else None
        out.append(Responder(
            mmsi=v.mmsi, name=v.name, kind=v.kind,
            distance_nm=round(nm, 1),
            eta_hours=round(eta, 1) if eta else None,
            sar_capable=v.can_assist, armed=v.kind in ARMED,
        ))
    # Dedicated SAR assets first at comparable range, then pure proximity.
    out.sort(key=lambda r: (r.distance_nm - (60.0 if r.sar_capable else 0.0)))
    return out[:limit]


def _position(lat: float, lon: float) -> str:
    ns, ew = ("N" if lat >= 0 else "S"), ("E" if lon >= 0 else "W")
    return f"{abs(lat):.3f}{ns} {abs(lon):.3f}{ew}"


def build_packets(incident: Incident, vessel: Ship,
                  responders: list[Responder]) -> list[Packet]:
    t = incident.triage
    assert t is not None, "packets requested before triage"

    region, mrcc = sar_region(vessel.lat, vessel.lon)
    pos = _position(vessel.lat, vessel.lon)
    unknowns = "\n".join(f"  - {u}" for u in t.unknowns) or "  - none declared"
    # The response asset has to match the incident, not merely be nearby and willing.
    # A tug is SAR-capable and sorts to the top of the responder list, so taking the
    # head of that list sent a tug a rules-of-engagement tasking for an armed
    # boarding. For a security incident the asset must be armed, or there is no asset
    # draft at all and the recommendation says plainly that none was in range.
    # Same call the recommendation makes, so the two can never name different ships.
    want, asset, closest = assign(t, responders)

    packets = [
        Packet(
            recipient_class="mrcc",
            recipient_name=f"{mrcc} ({region})",
            subject=f"[{t.severity.name}] {t.type.value}: {vessel.name} ({vessel.mmsi})",
            body=(
                f"INCIDENT CLASSIFICATION: {t.type.value}\n"
                f"SEVERITY: {t.severity.name}\n"
                f"CONFIDENCE: {t.confidence:.2f} (classifier: {t.provider})\n\n"
                f"VESSEL: {vessel.name}\nMMSI: {vessel.mmsi}\n"
                f"FLAG: {vessel.flag}\nTYPE: {vessel.kind}\n"
                f"CARGO: {vessel.cargo or 'not declared'}\n"
                f"PERSONS ON BOARD: {vessel.pob}\n\n"
                f"POSITION: {pos}\n"
                f"COURSE/SPEED: {vessel.course:.0f}T / {vessel.speed_kn:.1f} kn\n"
                f"NAV STATUS: {vessel.nav_status}\n"
                f"SAR REGION: {region}\n\n"
                f"UNCONFIRMED AT TIME OF SENDING:\n{unknowns}\n\n"
                f"BASIS: {t.rationale}\n\n{GMDSS_FOOTER}"
            ),
        ),
    ]

    if closest:
        packets.append(Packet(
            recipient_class="merchant",
            recipient_name=f"{closest.name} ({closest.mmsi})",
            recipient_mmsi=closest.mmsi,
            subject=f"Request to assist. Vessel in distress {closest.distance_nm} nm from you",
            body=(
                f"Master, {closest.name}.\n\n"
                f"A vessel in your vicinity is in distress and you may be the closest "
                f"hull. This is a request under the SOLAS duty to render assistance.\n\n"
                f"CASUALTY: {vessel.name} ({vessel.mmsi}), {vessel.pob} persons on board\n"
                f"TYPE / CARGO: {vessel.kind}, {vessel.cargo or 'not declared'}\n"
                f"POSITION: {pos}\n"
                f"NATURE: {t.type.value} ({t.severity.name} severity)\n"
                f"YOUR RANGE: {closest.distance_nm} nm"
                + (f", estimated {closest.eta_hours} h at current speed\n"
                   if closest.eta_hours else "\n")
                + f"\nHAZARDS TO YOU ON APPROACH:\n{_hazards(t.type.value)}\n\n"
                f"If you are able to divert, advise the responsible rescue coordination "
                f"centre and this station. If you are not able to divert, say so. A "
                f"declined request is still information we need.\n\n{GMDSS_FOOTER}"
            ),
        ))

    if asset:
        a = asset
        packets.append(Packet(
            recipient_class="naval",
            recipient_name=f"{a.name} ({a.kind}, {a.mmsi})",
            recipient_mmsi=a.mmsi,
            subject=f"SAR tasking request: {t.type.value}, {a.distance_nm} nm",
            body=(
                f"CASUALTY: {vessel.name} ({vessel.mmsi})\n"
                f"POSITION: {pos}\nPOB: {vessel.pob}\n"
                f"CLASSIFICATION: {t.type.value} / {t.severity.name} "
                f"(confidence {t.confidence:.2f})\n"
                f"RANGE FROM YOU: {a.distance_nm} nm"
                + (f", ETA {a.eta_hours} h\n" if a.eta_hours else "\n")
                + f"\nTHREAT PICTURE: {_threat(t.type.value)}\n\n"
                f"UNCONFIRMED:\n{unknowns}\n\n"
                f"This is a request for tasking, not a tasking order. Rules of "
                f"engagement remain a matter for your chain of command.\n\n{GMDSS_FOOTER}"
            ),
        ))

    packets.append(Packet(
        recipient_class="manager",
        recipient_name=f"Designated Person Ashore, {vessel.flag} flag",
        subject=f"{vessel.name}: {t.type.value}, {t.severity.name}",
        body=(
            f"Full picture for the DPA.\n\n"
            f"VESSEL: {vessel.name} ({vessel.mmsi}), {vessel.flag} flag, {vessel.kind}\n"
            f"POB: {vessel.pob}\nCARGO: {vessel.cargo or 'not declared'}\n"
            f"POSITION: {pos}\nCORRIDOR: {vessel.corridor}\n\n"
            f"REPORT AS RECEIVED:\n{incident.report_text or '(no voice or written report)'}\n\n"
            f"TRIAGE: {t.type.value} / {t.severity.name}, confidence {t.confidence:.2f}, "
            f"classifier {t.provider} ({t.latency_ms} ms)\n"
            f"BASIS: {t.rationale}\n\n"
            f"UNCONFIRMED:\n{unknowns}\n\n"
            f"RESPONSIBLE AUTHORITY: {mrcc}, {region}\n"
            f"NEAREST ASSETS: " + ", ".join(
                f"{r.name} ({r.distance_nm} nm)" for r in responders[:3]) + "\n\n"
            f"Next of kin notification has been drafted and is held pending your "
            f"instruction. It has not been sent.\n\n{GMDSS_FOOTER}"
        ),
    ))

    packets.append(Packet(
        recipient_class="next_of_kin",
        recipient_name="Next of kin: DRAFT, hold for company welfare officer",
        subject=f"Regarding {vessel.name}",
        body=(
            f"DRAFT ONLY. This must be read, edited and sent by a named human being "
            f"in the company's welfare function. It must not be sent as written and "
            f"it must not be sent by this system.\n\n"
            f"---\n\n"
            f"We are contacting you about {vessel.name}, on which your relative is "
            f"serving. Earlier today the vessel reported an incident and shore "
            f"authorities are involved. We do not yet have confirmed information "
            f"about individual crew members.\n\n"
            f"We will call you again as soon as we have something confirmed, whether "
            f"or not there is news. You can reach the company's welfare line at any "
            f"hour.\n\n---\n\n"
            f"Do not release the vessel position, the incident classification, or the "
            f"confidence figure to next of kin. None of it is confirmed and all of it "
            f"will be quoted back.\n\n{GMDSS_FOOTER}"
        ),
    ))

    classified = Action(basis="classification", text=(
        f"{t.provider} read the report and telemetry as {t.type.value}, {t.severity.name} "
        f"severity, confidence {t.confidence:.2f}. Basis: {t.rationale}"))
    why = {
        "mrcc": [
            classified,
            Action(basis="geometry", text=f"The casualty is at {pos}, inside {region}. "
                   f"{mrcc} holds coordination authority for that area."),
            Action(basis="policy", text="Every incident goes to the responsible rescue centre "
                   "first. It tasks ships; no request from this station substitutes for that."),
        ],
        "manager": [Action(basis="policy", text=(
            "Every incident is reported to the ship's Designated Person Ashore. Held because it "
            "starts the company response (insurers, salvage, families), not a rescue."))],
        "next_of_kin": [Action(basis="policy", text=(
            "Drafted so the company has wording ready. Never sent by this system: a named "
            "welfare officer rewrites and sends it."))],
    }
    if asset:
        passed = [r for r in responders if r.distance_nm < asset.distance_nm]
        why["naval"] = [
            classified,
            Action(basis="policy", text=f"Standing procedure for {t.type.value}: {_WHY[want]}"),
            Action(basis="geometry", text=f"{asset.name} ({asset.kind}) is the closest match "
                   f"in range: {_range(asset)}."),
            *([Action(basis="geometry", text="Nearer but passed over, wrong capability for this "
                      "incident: " + ", ".join(f"{r.name} ({r.kind}, {r.distance_nm} nm)"
                                               for r in passed[:3]) + ".")] if passed else []),
            Action(basis="policy", text="Drafted as a request, not an order. The rescue centre "
                   "and the asset's own command decide whether it goes."),
        ]
    if closest:
        why["merchant"] = [
            classified,
            Action(basis="policy", text=(
                f"Standing procedure for {t.type.value}: {_WHY['any']}" if want == "any" else
                "SOLAS obliges any master who can help safely to do so. The nearest ship that "
                "is not the tasked asset gets this request, so two drafts reach two bridges.")),
            Action(basis="geometry", text=f"{closest.name} ({closest.kind}) is the nearest such ship: {_range(closest)}."),
            Action(basis="policy", text=f"Hazards written into the draft for {t.type.value}: "
                   + " ".join(_hazards(t.type.value).split())),
        ]
    for p in packets:
        p.reasoning = why.get(p.recipient_class, [])
    return packets



# ---- response doctrine -----------------------------------------------------
#
# What kind of help a given classification actually needs, and what an operator
# must not do. This is a lookup, not an inference, and deliberately so.
#
# The classification is the model's judgement and the console labels it as such.
# The tasking that follows from it is standing policy: reproducible, identical on
# every replay of the same scenario, and defensible in an inquiry in a way that
# "the model suggested the frigate that afternoon" is not. An LLM belongs on the
# reading of a garbled radio report, not on the decision to send armed men.
#
# `want` selects the asset class: armed (naval/coastguard), sar (any SAR-capable
# hull), towage (tug first), any (nearest hull, speed over capability), none.
DOCTRINE: dict[str, tuple[str, list[str], str]] = {
    "Unknown": ("none", [
        "Establish voice contact on VHF 16 and the vessel's satellite terminal.",
        "Hold the merchant and response drafts until the nature of the casualty is known.",
    ], "A beacon with no voice contact does not name an incident. Do not dispatch on a guess."),
    "Piracy": ("armed", [
        "Alert the regional piracy reporting centre and the flag state.",
        "Advise the master to hold full sea speed, continue evasive steering and keep "
        "the crew in the citadel.",
    ], "Merchant traffic must not close an active boarding without escort. The duty to "
       "assist does not oblige a master to enter a threat area."),
    "Attack": ("armed", [
        "Notify the flag state and war-risk underwriters.",
        "Advise the master on damage control and, if the hull is compromised, "
        "abandonment readiness.",
    ], "The area is under weapon employment. No merchant diversion without a naval picture."),
    "Fire": ("sar", [
        "Ask the master for fire location, boundary cooling status and whether fixed "
        "suppression has been released.",
        "Warn nearby traffic to approach from upwind.",
    ], "Check the cargo before tasking anyone alongside. A hazardous cargo makes an "
       "assisting hull a second casualty."),
    "Flooding": ("sar", [
        "Ask for the compartment flooded, the list angle, and whether the pumps are holding.",
        "Alert salvage and the P&I club now. A flooding casualty becomes a salvage case fast.",
    ], "Do not moor alongside an unstable casualty."),
    "Collision": ("sar", [
        "Establish whether both hulls are accounted for and whether anyone is in the water.",
        "Alert the coastal state for pollution response if either hull is holed.",
    ], "Persons and debris possibly in the water. Traffic in the area must reduce speed."),
    "Grounding": ("towage", [
        "Ask for state of tide, soundings around the hull, and any pollution observed.",
        "Alert the coastal state. A grounding is a pollution event before it is a rescue one.",
    ], "Do not send a deep-draft hull inside the casualty's safe contour."),
    "MachineryFailure": ("towage", [
        "Establish whether the vessel is drifting toward a hazard, and how long until it is.",
        "Treat as towage and commercial salvage unless the drift is dangerous.",
    ], "Not a SAR case yet. Do not spend a scarce rescue asset on it if a tug will do."),
    "MedicalEvacuation": ("sar", [
        "Get the patient's condition and observations to a telemedical advice service.",
        "Establish whether the casualty is within helicopter range of a shore base.",
    ], "A diversion to the nearest port is sometimes faster than a winch. Compare both "
       "before tasking."),
    "ManOverboard": ("any", [
        "Record the time and position of last sighting. Every minute moves the search datum.",
        "Ask the master to begin a Williamson turn and post all available lookouts.",
    ], "Survival time in the water is the binding constraint. The nearest hull beats the "
       "best-equipped one."),
    "CrewAbandonment": ("sar", [
        "Establish how many survival craft launched and how many persons are accounted for.",
        "Ask all traffic in range to rig recovery and post lookouts.",
    ], "Persons in the water. Every hull in range matters, not only the one tasked."),
}

# Why an asset class was asked for, and what it means when there is not one in range.
_WHY = {
    "armed": "Armed response. This is a security incident before it is a rescue one.",
    "sar": "Dedicated rescue capability, closest of those in range.",
    "towage": "Towage, not rescue. This casualty needs a line, not a search.",
    "any": "Nearest hull. Speed of arrival outweighs equipment here.",
}
_NONE = {
    "armed": "No naval or coastguard asset is in range. Merchant traffic is not an "
             "appropriate first responder to a security incident: escalate to the "
             "MRCC and the regional naval coordination authority before tasking anyone.",
    "sar": "No dedicated SAR asset is in range.",
    "towage": "No tug is in range.",
    "any": "Nothing is in range.",
}
# Strict test first, then what we will settle for. `armed` has no fallback on purpose:
# the absence of an armed asset is the finding, and papering over it with the nearest
# tug is the failure this table exists to prevent.
_FALLBACK = {
    "armed": [lambda r: r.armed],
    "sar": [lambda r: r.sar_capable],
    "towage": [lambda r: r.kind == "tug", lambda r: r.sar_capable],
    "any": [lambda r: True],
}


def pick_asset(responders: list[Responder], want: str) -> Responder | None:
    """Closest responder of the wanted class, relaxing the test only where the
    doctrine table allows it."""
    for test in _FALLBACK.get(want, []):
        hit = [r for r in responders if test(r)]
        if hit:
            return min(hit, key=lambda r: r.distance_nm)
    return None


def assign(triage: TriageResult,
           responders: list[Responder]) -> tuple[str, Responder | None, Responder | None]:
    """Who gets the tasking draft and who gets the duty-to-assist ask.

    Decided in one place because it used to be decided in two. The recommendation
    picked by doctrine and the drafts picked the nearest SAR-capable hull, so a
    man-overboard told the operator to task the container ship half a mile away
    while the draft on the same screen was addressed to a coastguard cutter an hour
    out. An operator given two answers has been given none.
    """
    want = DOCTRINE.get(triage.type.value, DOCTRINE["Unknown"])[0]
    if want == "none":
        # Nothing is established. Drafting a tasking off a bare beacon is the guess
        # this system exists not to make; the MRCC packet is the whole response.
        return want, None, None
    if want == "any":
        # Speed of arrival is the point. The nearest hull is the tasking, and it gets
        # the duty-to-assist draft, not a rules-of-engagement one written for a frigate.
        return want, None, min(responders, key=lambda r: r.distance_nm, default=None)
    asset = pick_asset(responders, want)
    # The duty-to-assist request goes to the nearest ship that is *not* the tasked
    # asset: two drafts to one bridge under two letterheads wastes one of them and
    # tells the casualty the same ship is coming twice.
    merchant = next((r for r in responders
                     if not r.sar_capable and (asset is None or r.mmsi != asset.mmsi)),
                    next((r for r in responders if asset is None or r.mmsi != asset.mmsi), None))
    return want, asset, merchant


def _range(r: Responder) -> str:
    return f"{r.distance_nm} nm" + (f", ETA {r.eta_hours} h" if r.eta_hours else ", not under way")


def recommend(triage: TriageResult, responders: list[Responder],
              mrcc: str, region: str) -> list[Action]:
    """The recommended course of action, in the order an operator should take it.

    Deliberately short. A watch officer reading this has a casualty on the screen
    and does not have time for prose, and a list long enough to need scrolling is a
    list whose last line never gets read.
    """
    _, lines, caution = DOCTRINE.get(triage.type.value, DOCTRINE["Unknown"])
    want, asset, merchant = assign(triage, responders)
    out: list[Action] = []

    # An unestablished classification outranks every other instruction on the page.
    if triage.type.value == "Unknown" or triage.confidence < 0.55:
        out.append(Action(
            text=f"Classification is not established (confidence {triage.confidence:.2f}). "
                 f"Establish voice contact before tasking anyone.",
            urgency="caution", basis="classification"))

    out.append(Action(
        text=f"Notify {mrcc}. It holds coordination authority for {region}, and nothing "
             f"below substitutes for that.",
        urgency="now", basis="policy"))

    # Names the hull that actually received a draft, never a second opinion.
    tasked = merchant if want == "any" else asset
    if want != "none":
        out.append(Action(
            text=(f"Task {tasked.name} ({tasked.kind}, {_range(tasked)}). {_WHY[want]}"
                  if tasked else _NONE[want]),
            urgency="now" if tasked else "caution", basis="geometry"))

    out += [Action(text=t, urgency="next", basis="policy") for t in lines]
    out.append(Action(text=caution, urgency="caution", basis="policy"))

    if triage.unknowns:
        out.append(Action(
            text="Ask the bridge to close the declared unknowns: "
                 + "; ".join(triage.unknowns) + ".",
            urgency="next", basis="classification"))
    return out


def _hazards(incident_type: str) -> str:
    return {
        "Piracy": "  Armed skiffs may still be in the area. Consider approaching only\n"
                  "  with naval escort. Harden the ship before closing.",
        "Attack": "  Area is subject to aerial and surface attack. Assess your own risk\n"
                  "  before diverting. You are not obliged to enter a threat area.",
        "Fire": "  Fire aboard, possible smoke and heat on the leeward side.\n"
                "  Approach from upwind.",
        "Flooding": "  Casualty may be listing and unstable. Do not moor alongside.",
        "Collision": "  Debris and persons possibly in the water. Reduce speed, post\n"
                     "  extra lookouts.",
        "Grounding": "  Casualty is aground. Uncharted or shoaling water in the\n"
                     "  immediate area. Do not close inside your own safe contour.",
        "CrewAbandonment": "  Survival craft and persons in the water. Reduce speed,\n"
                           "  post extra lookouts, rig recovery.",
        "ManOverboard": "  Person in the water. Reduce speed, post extra lookouts.",
    }.get(incident_type, "  Nature of the incident is not confirmed. Approach with caution.")


def _threat(incident_type: str) -> str:
    return {
        "Piracy": "Armed hostile actors, small craft, likely boarding attempt.",
        "Attack": "Aerial or surface weapon employment against merchant shipping.",
    }.get(incident_type, "No hostile actor indicated. Humanitarian SAR tasking.")
